"""Shared schema expectations for ORM and database tests."""

EXPECTED_TABLES = {
    "batch_runs",
    "club_memberships",
    "clubs",
    "configuration_profile_versions",
    "configuration_profiles",
    "export_runs",
    "first_names",
    "generation_runs",
    "generation_runtime_metrics",
    "job_stage_progress",
    "job_status",
    "last_names",
    "match_games",
    "match_team_players",
    "match_teams",
    "matches",
    "monthly_batches",
    "player_assessment_history",
    "player_rating_history",
    "player_registrations",
    "players",
    "ratings_update_log",
    "raw_first_names",
    "raw_last_names",
    "raw_metro_areas",
    "raw_pickleball_club_distributions",
    "raw_pickleball_club_names",
    "raw_seed_load_errors",
    "raw_seed_load_runs",
    "raw_state_prov_biases",
    "regions",
    "team_memberships",
    "teams",
    "tournaments",
    "uploaded_files",
    "validation_results",
    "student_dataset_releases",
    "student_dataset_release_files",
    "student_dataset_comparisons",
    "team_lifecycle_events",
    "tournament_division_results",
    "tournament_events",
    "tournament_group_results",
    "tournament_official_games",
    "tournament_official_matches",
    "tournament_simulation_runs",
    "tournament_student_groups",
    "tournament_submissions",
    "tournament_team_results",
}

STALE_SPLIT_NAME_TABLES = {
    "usa_first_names",
    "usa_last_names",
    "canada_first_names",
    "canada_last_names",
}

EXPECTED_INDEXES = {
    "idx_assessment_batch",
    "idx_assessment_player_date",
    "idx_batch_runs_batch",
    "idx_batch_runs_status",
    "idx_club_memberships_club",
    "idx_club_memberships_dates",
    "idx_club_memberships_player",
    "idx_club_memberships_primary",
    "idx_clubs_generation_run",
    "idx_clubs_region",
    "idx_clubs_type",
    "idx_configuration_profiles_active",
    "idx_configuration_versions_profile",
    "idx_configuration_versions_schema",
    "idx_configuration_versions_lifecycle",
    "idx_export_runs_batch",
    "idx_export_runs_created",
    "idx_export_runs_type",
    "idx_first_names_country",
    "idx_first_names_lookup",
    "idx_first_names_probability",
    "idx_generation_runs_started",
    "idx_generation_runs_status",
    "idx_generation_runtime_metrics_batch",
    "idx_generation_runtime_metrics_event",
    "idx_generation_runtime_metrics_run",
    "idx_generation_runtime_metrics_stage",
    "idx_generation_runtime_metrics_subphase",
    "idx_job_stage_progress_batch",
    "idx_job_stage_progress_generation_run",
    "idx_job_stage_progress_heartbeat",
    "idx_job_stage_progress_job",
    "idx_job_stage_progress_status",
    "idx_job_status_started",
    "idx_job_status_status",
    "idx_job_status_type",
    "idx_last_names_country",
    "idx_last_names_country_name_lookup",
    "idx_last_names_lookup",
    "idx_last_names_state_name_lookup",
    "idx_match_games_match",
    "idx_match_games_winner",
    "idx_match_team_players_player",
    "idx_match_team_players_team",
    "idx_match_teams_match",
    "idx_matches_batch",
    "idx_matches_date",
    "idx_matches_region",
    "idx_matches_tournament",
    "idx_matches_type",
    "idx_monthly_batches_generation_run",
    "idx_monthly_batches_month",
    "idx_monthly_batches_status",
    "idx_player_registrations_batch",
    "idx_player_registrations_month",
    "idx_player_registrations_player",
    "idx_players_generation_run",
    "idx_players_region",
    "idx_players_registration_date",
    "idx_players_status",
    "idx_raw_club_distributions_country_state",
    "idx_raw_club_distributions_load_run",
    "idx_raw_club_names_country_state",
    "idx_raw_club_names_load_run",
    "idx_raw_club_names_seed",
    "idx_raw_first_names_load_run",
    "idx_raw_first_names_lookup",
    "idx_raw_last_names_country",
    "idx_raw_last_names_load_run",
    "idx_raw_last_names_name",
    "idx_raw_metro_areas_country_state",
    "idx_raw_metro_areas_load_run",
    "idx_raw_metro_areas_probability",
    "idx_raw_seed_load_errors_code",
    "idx_raw_seed_load_errors_load_run",
    "idx_raw_seed_load_runs_job",
    "idx_raw_seed_load_runs_dataset",
    "idx_raw_seed_load_runs_started",
    "idx_raw_seed_load_runs_status",
    "idx_raw_state_prov_biases_country_state",
    "idx_raw_state_prov_biases_load_run",
    "idx_raw_state_prov_biases_lookup",
    "idx_rating_batch",
    "idx_rating_player_date",
    "idx_ratings_update_log_batch",
    "idx_student_dataset_release_files_release",
    "idx_student_dataset_release_files_table",
    "idx_student_dataset_comparisons_clean_run",
    "idx_student_dataset_comparisons_created",
    "idx_student_dataset_comparisons_status",
    "idx_student_dataset_comparisons_tainted_run",
    "idx_student_dataset_releases_generation_run",
    "idx_student_dataset_releases_status",
    "idx_team_memberships_dates",
    "idx_team_memberships_player",
    "idx_team_memberships_team",
    "idx_team_lifecycle_events_batch",
    "idx_team_lifecycle_events_date",
    "idx_team_lifecycle_events_run",
    "idx_team_lifecycle_events_team",
    "idx_teams_country",
    "idx_teams_formation_date",
    "idx_teams_status",
    "idx_teams_type",
    "idx_tournaments_region",
    "idx_tournaments_start_date",
    "idx_tournament_division_results_division",
    "idx_tournament_division_results_run",
    "idx_tournament_events_date",
    "idx_tournament_events_generation_run",
    "idx_tournament_events_source_batch",
    "idx_tournament_events_status",
    "idx_tournament_group_results_group",
    "idx_tournament_group_results_run",
    "idx_tournament_official_games_match",
    "idx_tournament_official_matches_division",
    "idx_tournament_official_matches_run",
    "idx_tournament_simulation_runs_event",
    "idx_tournament_simulation_runs_job",
    "idx_tournament_simulation_runs_status",
    "idx_tournament_simulation_runs_type",
    "idx_tournament_student_groups_event",
    "idx_tournament_submissions_event",
    "idx_tournament_submissions_group",
    "idx_tournament_submissions_team",
    "idx_tournament_team_results_division",
    "idx_tournament_team_results_run",
    "idx_tournament_team_results_team",
    "idx_uploaded_files_status",
    "idx_uploaded_files_timestamp",
    "idx_validation_results_batch",
    "idx_validation_results_rule",
    "idx_validation_results_severity",
    "uq_configuration_versions_single_valid",
}

EXPECTED_CHECK_CONSTRAINTS = {
    "batch_runs": {"chk_run_status"},
    "club_memberships": {"chk_membership_dates"},
    "clubs": {"chk_club_type", "chk_court_counts"},
    "configuration_profile_versions": {
        "chk_configuration_lifecycle_status",
        "chk_configuration_version_number",
    },
    "job_stage_progress": {
        "chk_job_stage_progress_percent",
        "chk_job_stage_progress_status",
    },
    "export_runs": {"chk_export_format"},
    "first_names": {
        "chk_first_names_country",
        "chk_first_names_freq",
        "chk_first_names_gender",
    },
    "generation_runs": {"chk_generation_status"},
    "generation_runtime_metrics": {
        "chk_generation_runtime_metric_elapsed",
        "chk_generation_runtime_metric_event_type",
    },
    "job_status": {"chk_job_status", "chk_percent_complete"},
    "last_names": {"chk_last_names_country", "chk_last_names_freq"},
    "match_games": {
        "chk_game_number",
        "chk_game_scores_nonnegative",
        "chk_game_target_score",
        "chk_game_win_by",
        "chk_game_winning_team",
    },
    "match_team_players": {"chk_player_position"},
    "match_teams": {"chk_match_team_pairing_source", "chk_team_number"},
    "matches": {"chk_match_predicted_winning_team", "chk_match_type"},
    "monthly_batches": {"chk_batch_type", "chk_processing_status"},
    "player_assessment_history": {"chk_assessment_confidence"},
    "player_rating_history": {"chk_confidence_score", "chk_rating_value"},
    "ratings_update_log": {
        "chk_rating_log_actual_share",
        "chk_rating_log_after",
        "chk_rating_log_before",
        "chk_rating_log_expected_share",
        "chk_rating_log_games_played",
        "chk_rating_log_games_won",
        "chk_rating_log_match_number",
        "chk_rating_log_match_won",
        "chk_rating_log_team_number",
    },
    "players": {"chk_player_birth_date", "chk_player_status"},
    "raw_first_names": {
        "chk_raw_first_names_country",
        "chk_raw_first_names_freq",
        "chk_raw_first_names_gender",
    },
    "raw_last_names": {"chk_raw_last_names_country", "chk_raw_last_names_freq"},
    "raw_metro_areas": {
        "chk_raw_metro_country",
        "chk_raw_metro_population",
        "chk_raw_metro_probability",
    },
    "raw_pickleball_club_distributions": {
        "chk_raw_club_dist_count",
        "chk_raw_club_dist_country",
    },
    "raw_pickleball_club_names": {"chk_raw_club_names_country"},
    "raw_seed_load_runs": {
        "chk_raw_seed_load_counts",
        "chk_raw_seed_load_status",
    },
    "raw_state_prov_biases": {
        "chk_raw_state_bias_country",
        "chk_raw_state_bias_multiplier",
    },
    "team_memberships": {"chk_membership_dates", "chk_position"},
    "teams": {
        "chk_team_country",
        "chk_team_dates",
        "chk_team_status",
        "chk_team_type",
    },
    "team_lifecycle_events": {"chk_team_lifecycle_event_type"},
    "tournament_division_results": {
        "chk_tournament_division_match_count",
        "chk_tournament_division_result_country",
        "chk_tournament_division_result_division",
        "chk_tournament_division_team_count",
    },
    "tournament_events": {"chk_tournament_event_status"},
    "tournament_group_results": {"chk_tournament_group_result_rank"},
    "tournament_official_games": {
        "chk_tournament_official_game_number",
        "chk_tournament_official_game_scores",
        "chk_tournament_official_game_target",
        "chk_tournament_official_game_win_by",
        "chk_tournament_official_game_winner",
    },
    "tournament_official_matches": {
        "chk_tournament_official_match_country",
        "chk_tournament_official_match_distinct_teams",
        "chk_tournament_official_match_division",
        "chk_tournament_official_match_number",
    },
    "tournament_simulation_runs": {
        "chk_tournament_simulation_iterations",
        "chk_tournament_simulation_run_status",
        "chk_tournament_simulation_run_type",
    },
    "tournament_submissions": {
        "chk_tournament_submission_country",
        "chk_tournament_submission_division",
        "chk_tournament_submission_validation_status",
    },
    "tournament_team_results": {
        "chk_tournament_team_result_country",
        "chk_tournament_team_result_division",
        "chk_tournament_team_result_rank",
    },
    "tournaments": {"chk_tournament_dates"},
    "uploaded_files": {"chk_file_size"},
    "student_dataset_releases": {
        "chk_student_release_status",
        "chk_student_release_type",
    },
    "student_dataset_comparisons": {
        "chk_student_dataset_comparison_counts",
        "chk_student_dataset_comparison_status",
    },
    "validation_results": {"chk_severity"},
}

EXPECTED_UNIQUE_CONSTRAINTS = {
    "clubs": {("region_id", "club_name")},
    "configuration_profile_versions": {("profile_id", "version_number")},
    "configuration_profiles": {("profile_name",)},
    "job_status": {("job_id",)},
    "job_stage_progress": {("job_status_id", "batch_id", "stage_name")},
    "match_games": {("match_id", "game_number")},
    "match_team_players": {("match_team_id", "player_id")},
    "match_teams": {("match_id", "team_number")},
    "monthly_batches": {("generation_run_id", "batch_month")},
    "player_registrations": {("player_id", "batch_id")},
    "players": {("external_player_key",)},
    "raw_pickleball_club_distributions": {
        ("load_run_id", "country_code", "state_province_code"),
    },
    "raw_pickleball_club_names": {("load_run_id", "club_seed")},
    "regions": {("country_code", "state_province_code", "region_name")},
    "team_memberships": {("team_id", "player_id", "joined_date")},
    "tournament_division_results": {
        ("simulation_run_id", "slot_country_code", "slot_division"),
    },
    "tournament_group_results": {("simulation_run_id", "student_group_id")},
    "tournament_official_games": {("official_match_id", "game_number")},
    "tournament_official_matches": {("simulation_run_id", "match_number")},
    "tournament_student_groups": {
        ("event_id", "external_group_key"),
        ("event_id", "group_name"),
    },
    "tournament_submissions": {
        ("event_id", "student_group_id", "slot_country_code", "slot_division"),
    },
    "tournament_team_results": {
        ("simulation_run_id", "slot_country_code", "slot_division", "team_id"),
    },
}

EXPECTED_FOREIGN_KEYS = {
    "batch_runs": {"batch_id->monthly_batches.id"},
    "club_memberships": {
        "club_id->clubs.id",
        "generation_run_id->generation_runs.id",
        "player_id->players.id",
    },
    "clubs": {"generation_run_id->generation_runs.id", "region_id->regions.id"},
    "configuration_profile_versions": {
        "profile_id->configuration_profiles.id",
    },
    "export_runs": {"batch_id->monthly_batches.id"},
    "generation_runtime_metrics": {
        "batch_id->monthly_batches.id",
        "generation_run_id->generation_runs.id",
    },
    "job_stage_progress": {
        "batch_id->monthly_batches.id",
        "generation_run_id->generation_runs.id",
        "job_status_id->job_status.id",
    },
    "match_games": {"match_id->matches.id"},
    "match_team_players": {
        "match_team_id->match_teams.id",
        "player_id->players.id",
    },
    "match_teams": {"match_id->matches.id", "source_team_id->teams.id"},
    "matches": {
        "batch_id->monthly_batches.id",
        "region_id->regions.id",
        "tournament_id->tournaments.id",
    },
    "monthly_batches": {"generation_run_id->generation_runs.id"},
    "player_assessment_history": {
        "batch_id->monthly_batches.id",
        "player_id->players.id",
    },
    "player_rating_history": {
        "batch_id->monthly_batches.id",
        "player_id->players.id",
    },
    "player_registrations": {
        "assigned_region_id->regions.id",
        "batch_id->monthly_batches.id",
        "player_id->players.id",
    },
    "players": {
        "generation_run_id->generation_runs.id",
        "home_region_id->regions.id",
    },
    "ratings_update_log": {
        "batch_id->monthly_batches.id",
        "generation_run_id->generation_runs.id",
        "match_id->matches.id",
        "match_team_id->match_teams.id",
        "player_id->players.id",
    },
    "raw_first_names": {"load_run_id->raw_seed_load_runs.id"},
    "raw_last_names": {"load_run_id->raw_seed_load_runs.id"},
    "raw_metro_areas": {"load_run_id->raw_seed_load_runs.id"},
    "raw_seed_load_runs": {"job_status_id->job_status.id"},
    "raw_pickleball_club_distributions": {
        "load_run_id->raw_seed_load_runs.id",
    },
    "raw_pickleball_club_names": {"load_run_id->raw_seed_load_runs.id"},
    "raw_seed_load_errors": {"load_run_id->raw_seed_load_runs.id"},
    "raw_state_prov_biases": {"load_run_id->raw_seed_load_runs.id"},
    "student_dataset_release_files": {
        "release_id->student_dataset_releases.id",
    },
    "student_dataset_comparisons": {
        "clean_generation_run_id->generation_runs.id",
        "tainted_generation_run_id->generation_runs.id",
    },
    "student_dataset_releases": {
        "generation_run_id->generation_runs.id",
    },
    "team_memberships": {"player_id->players.id", "team_id->teams.id"},
    "teams": {"generation_run_id->generation_runs.id"},
    "tournament_division_results": {
        "champion_team_id->teams.id",
        "simulation_run_id->tournament_simulation_runs.id",
    },
    "tournament_events": {
        "generation_run_id->generation_runs.id",
        "source_batch_id->monthly_batches.id",
    },
    "tournament_group_results": {
        "simulation_run_id->tournament_simulation_runs.id",
        "student_group_id->tournament_student_groups.id",
    },
    "tournament_official_games": {
        "official_match_id->tournament_official_matches.id",
    },
    "tournament_official_matches": {
        "simulation_run_id->tournament_simulation_runs.id",
        "team_one_id->teams.id",
        "team_two_id->teams.id",
        "winning_team_id->teams.id",
    },
    "tournament_simulation_runs": {
        "event_id->tournament_events.id",
        "job_status_id->job_status.id",
    },
    "tournament_student_groups": {"event_id->tournament_events.id"},
    "tournament_submissions": {
        "event_id->tournament_events.id",
        "student_group_id->tournament_student_groups.id",
        "team_id->teams.id",
    },
    "tournament_team_results": {
        "simulation_run_id->tournament_simulation_runs.id",
        "team_id->teams.id",
    },
    "tournaments": {"generation_run_id->generation_runs.id", "region_id->regions.id"},
    "validation_results": {"batch_id->monthly_batches.id"},
}

EXPECTED_SERVER_DEFAULTS = {
    "generation_runs": {"status": "'not_started'"},
    "configuration_profile_versions": {"lifecycle_status": "'valid'"},
    "job_stage_progress": {
        "progress_current": "0",
        "status": "'pending'",
    },
    "configuration_profiles": {"is_active": "true"},
    "monthly_batches": {
        "batch_type": "'future_increment'",
        "processing_status": "'pending'",
    },
    "match_games": {
        "target_score": "11",
        "win_by": "2",
    },
    "player_registrations": {"registration_source": "'synthetic'"},
    "players": {
        "external_player_key": "gen_random_uuid()",
        "player_status": "'ACTIVE'",
    },
    "regions": {"competitiveness_multiplier": "1.0"},
    "raw_seed_load_runs": {"status": "'pending'"},
    "student_dataset_comparisons": {
        "compared_release_count": "0",
        "missing_clean_release_count": "0",
        "missing_tainted_release_count": "0",
        "status": "'succeeded'",
        "total_issue_count": "0",
    },
    "student_dataset_releases": {"status": "'pending'"},
    "tournament_events": {"status": "'draft'"},
    "tournament_official_games": {
        "target_score": "11",
        "win_by": "2",
    },
    "tournament_simulation_runs": {"status": "'pending'"},
    "tournament_submissions": {"validation_status": "'pending'"},
}
