"""Shared schema expectations for ORM and database tests."""

EXPECTED_TABLES = {
    "batch_runs",
    "club_memberships",
    "clubs",
    "export_runs",
    "first_names",
    "generation_runs",
    "job_status",
    "last_names",
    "match_games",
    "match_team_players",
    "match_teams",
    "matches",
    "monthly_batches",
    "player_assessment_history",
    "player_rating_history",
    "player_registrations",
    "players",
    "raw_first_names",
    "raw_last_names",
    "raw_metro_areas",
    "raw_pickleball_club_distributions",
    "raw_pickleball_club_names",
    "raw_seed_load_errors",
    "raw_seed_load_runs",
    "raw_state_prov_biases",
    "regions",
    "team_memberships",
    "teams",
    "tournaments",
    "uploaded_files",
    "validation_results",
}

STALE_SPLIT_NAME_TABLES = {
    "usa_first_names",
    "usa_last_names",
    "canada_first_names",
    "canada_last_names",
}

EXPECTED_INDEXES = {
    "idx_assessment_batch",
    "idx_assessment_player_date",
    "idx_batch_runs_batch",
    "idx_batch_runs_status",
    "idx_club_memberships_club",
    "idx_club_memberships_dates",
    "idx_club_memberships_player",
    "idx_club_memberships_primary",
    "idx_clubs_generation_run",
    "idx_clubs_region",
    "idx_clubs_type",
    "idx_export_runs_batch",
    "idx_export_runs_created",
    "idx_export_runs_type",
    "idx_first_names_country",
    "idx_first_names_lookup",
    "idx_first_names_probability",
    "idx_generation_runs_started",
    "idx_generation_runs_status",
    "idx_job_status_started",
    "idx_job_status_status",
    "idx_job_status_type",
    "idx_last_names_country",
    "idx_last_names_lookup",
    "idx_match_games_match",
    "idx_match_games_winner",
    "idx_match_team_players_player",
    "idx_match_team_players_team",
    "idx_match_teams_match",
    "idx_matches_batch",
    "idx_matches_date",
    "idx_matches_region",
    "idx_matches_tournament",
    "idx_matches_type",
    "idx_monthly_batches_generation_run",
    "idx_monthly_batches_month",
    "idx_monthly_batches_status",
    "idx_player_registrations_batch",
    "idx_player_registrations_month",
    "idx_player_registrations_player",
    "idx_players_generation_run",
    "idx_players_region",
    "idx_players_registration_date",
    "idx_players_status",
    "idx_raw_club_distributions_country_state",
    "idx_raw_club_distributions_load_run",
    "idx_raw_club_names_country_state",
    "idx_raw_club_names_load_run",
    "idx_raw_club_names_seed",
    "idx_raw_first_names_load_run",
    "idx_raw_first_names_lookup",
    "idx_raw_last_names_country",
    "idx_raw_last_names_load_run",
    "idx_raw_last_names_name",
    "idx_raw_metro_areas_country_state",
    "idx_raw_metro_areas_load_run",
    "idx_raw_metro_areas_probability",
    "idx_raw_seed_load_errors_code",
    "idx_raw_seed_load_errors_load_run",
    "idx_raw_seed_load_runs_dataset",
    "idx_raw_seed_load_runs_started",
    "idx_raw_seed_load_runs_status",
    "idx_raw_state_prov_biases_country_state",
    "idx_raw_state_prov_biases_load_run",
    "idx_raw_state_prov_biases_lookup",
    "idx_rating_batch",
    "idx_rating_date_type",
    "idx_rating_player_date",
    "idx_rating_value",
    "idx_team_memberships_dates",
    "idx_team_memberships_player",
    "idx_team_memberships_team",
    "idx_teams_formation_date",
    "idx_teams_status",
    "idx_teams_type",
    "idx_tournaments_region",
    "idx_tournaments_start_date",
    "idx_uploaded_files_status",
    "idx_uploaded_files_timestamp",
    "idx_validation_results_batch",
    "idx_validation_results_rule",
    "idx_validation_results_severity",
}

EXPECTED_CHECK_CONSTRAINTS = {
    "batch_runs": {"chk_run_status"},
    "club_memberships": {"chk_membership_dates"},
    "clubs": {"chk_club_type", "chk_court_counts"},
    "export_runs": {"chk_export_format"},
    "first_names": {
        "chk_first_names_country",
        "chk_first_names_freq",
        "chk_first_names_gender",
    },
    "generation_runs": {"chk_generation_status"},
    "job_status": {"chk_job_status", "chk_percent_complete"},
    "last_names": {"chk_last_names_country", "chk_last_names_freq"},
    "match_games": {
        "chk_game_number",
        "chk_game_scores_nonnegative",
        "chk_game_target_score",
        "chk_game_win_by",
        "chk_game_winning_team",
    },
    "match_team_players": {"chk_player_position"},
    "match_teams": {"chk_team_number"},
    "matches": {"chk_match_type"},
    "monthly_batches": {"chk_batch_type", "chk_processing_status"},
    "player_assessment_history": {"chk_assessment_confidence"},
    "player_rating_history": {"chk_confidence_score", "chk_rating_value"},
    "players": {"chk_player_birth_date", "chk_player_status"},
    "raw_first_names": {
        "chk_raw_first_names_country",
        "chk_raw_first_names_freq",
        "chk_raw_first_names_gender",
    },
    "raw_last_names": {"chk_raw_last_names_country", "chk_raw_last_names_freq"},
    "raw_metro_areas": {
        "chk_raw_metro_country",
        "chk_raw_metro_population",
        "chk_raw_metro_probability",
    },
    "raw_pickleball_club_distributions": {
        "chk_raw_club_dist_count",
        "chk_raw_club_dist_country",
    },
    "raw_pickleball_club_names": {"chk_raw_club_names_country"},
    "raw_seed_load_runs": {
        "chk_raw_seed_load_counts",
        "chk_raw_seed_load_status",
    },
    "raw_state_prov_biases": {
        "chk_raw_state_bias_country",
        "chk_raw_state_bias_multiplier",
    },
    "team_memberships": {"chk_membership_dates", "chk_position"},
    "teams": {"chk_team_dates", "chk_team_status", "chk_team_type"},
    "tournaments": {"chk_tournament_dates"},
    "uploaded_files": {"chk_file_size"},
    "validation_results": {"chk_severity"},
}

EXPECTED_UNIQUE_CONSTRAINTS = {
    "clubs": {("region_id", "club_name")},
    "job_status": {("job_id",)},
    "match_games": {("match_id", "game_number")},
    "match_team_players": {("match_team_id", "player_id")},
    "match_teams": {("match_id", "team_number")},
    "monthly_batches": {("generation_run_id", "batch_month")},
    "player_registrations": {("player_id", "batch_id")},
    "players": {("external_player_key",)},
    "raw_pickleball_club_distributions": {
        ("load_run_id", "country_code", "state_province_code"),
    },
    "raw_pickleball_club_names": {("load_run_id", "club_seed")},
    "regions": {("country_code", "state_province_code", "region_name")},
    "team_memberships": {("team_id", "player_id", "joined_date")},
}

EXPECTED_FOREIGN_KEYS = {
    "batch_runs": {"batch_id->monthly_batches.id"},
    "club_memberships": {
        "club_id->clubs.id",
        "generation_run_id->generation_runs.id",
        "player_id->players.id",
    },
    "clubs": {"generation_run_id->generation_runs.id", "region_id->regions.id"},
    "export_runs": {"batch_id->monthly_batches.id"},
    "match_games": {"match_id->matches.id"},
    "match_team_players": {
        "match_team_id->match_teams.id",
        "player_id->players.id",
    },
    "match_teams": {"match_id->matches.id"},
    "matches": {
        "batch_id->monthly_batches.id",
        "region_id->regions.id",
        "tournament_id->tournaments.id",
    },
    "monthly_batches": {"generation_run_id->generation_runs.id"},
    "player_assessment_history": {
        "batch_id->monthly_batches.id",
        "player_id->players.id",
    },
    "player_rating_history": {
        "batch_id->monthly_batches.id",
        "player_id->players.id",
    },
    "player_registrations": {
        "assigned_region_id->regions.id",
        "batch_id->monthly_batches.id",
        "player_id->players.id",
    },
    "players": {
        "generation_run_id->generation_runs.id",
        "home_region_id->regions.id",
    },
    "raw_first_names": {"load_run_id->raw_seed_load_runs.id"},
    "raw_last_names": {"load_run_id->raw_seed_load_runs.id"},
    "raw_metro_areas": {"load_run_id->raw_seed_load_runs.id"},
    "raw_pickleball_club_distributions": {
        "load_run_id->raw_seed_load_runs.id",
    },
    "raw_pickleball_club_names": {"load_run_id->raw_seed_load_runs.id"},
    "raw_seed_load_errors": {"load_run_id->raw_seed_load_runs.id"},
    "raw_state_prov_biases": {"load_run_id->raw_seed_load_runs.id"},
    "team_memberships": {"player_id->players.id", "team_id->teams.id"},
    "teams": {"generation_run_id->generation_runs.id"},
    "tournaments": {"generation_run_id->generation_runs.id", "region_id->regions.id"},
    "validation_results": {"batch_id->monthly_batches.id"},
}

EXPECTED_SERVER_DEFAULTS = {
    "generation_runs": {"status": "'pending'"},
    "monthly_batches": {
        "batch_type": "'future_increment'",
        "processing_status": "'pending'",
    },
    "match_games": {
        "target_score": "11",
        "win_by": "2",
    },
    "player_registrations": {"registration_source": "'synthetic'"},
    "players": {
        "external_player_key": "gen_random_uuid()",
        "player_status": "'ACTIVE'",
    },
    "regions": {"competitiveness_multiplier": "1.0"},
    "raw_seed_load_runs": {"status": "'pending'"},
}
