"""Default configuration payload for the current generation profile version."""
from __future__ import annotations

from copy import deepcopy
from typing import Any


DEFAULT_CONFIG_PROFILE_NAME = "default"
DEFAULT_CONFIG_VERSION_NUMBER = 3
DEFAULT_CONFIG_SCHEMA_VERSION = "1.0"
DEFAULT_CONFIG_CREATED_BY = "system"


DEFAULT_CONFIG_PAYLOAD: dict[str, Any] = {
    "runtime": {
        "database_url": "postgresql://postgres:postgres@localhost:5432/pickleball",
        "database_echo": False,
        "environment_name": "local",
        "config_file_path": None,
        "ui_enabled": True,
        "max_preview_rows": 1000,
    },
    "simulation": {
        "master_seed": 42,
        "simulation_name": "NAPA_Olympic_Analytics_v1",
        "simulation_version": "1.0",
        "generation_run_mode": "full",
        "historical_batch_count": 12,
        "first_batch_month": "2024-01-01",
        "commit_strategy": "per_module",
        "batch_retry_policy": {
            "max_attempts": 1,
            "destructive_rerun_enabled": False,
        },
    },
    "instrumentation": {
        "players_enabled": True,
        "club_memberships_enabled": True,
        "teams_enabled": True,
        "matches_enabled": True,
        "ratings_enabled": True,
        "export_queries_enabled": False,
        "export_query_sql_text_enabled": False,
        "export_rss_guard_mb": None,
    },
    "raw_seed_data": {
        "raw_data_root": "data/raw",
        "supported_datasets": [
            "metro_areas_us",
            "metro_areas_ca",
            "first_names_us",
            "first_names_ca",
            "last_names_us",
            "last_names_ca",
            "state_prov_biases_us",
            "state_prov_biases_ca",
            "pickleball_club_names",
            "pickleball_club_distributions",
        ],
        "replace_production": False,
    },
    "player_generation": {
        "player_count": 100,
        "initial_player_count": None,
        "monthly_player_growth_rate": 0.02,
        "monthly_player_inactivation_rate": 0.01,
        "age_min": 12,
        "age_max": 85,
        "minimum_registration_age": 12,
        "age_distribution": {
            "under_18": 0.04,
            "18_29": 0.24,
            "30_44": 0.32,
            "45_59": 0.24,
            "60_74": 0.13,
            "75_plus": 0.03,
        },
        "gender_weights": {
            "male": 0.5,
            "female": 0.5,
        },
        "dominant_hand_weights": {
            "right": 0.88,
            "left": 0.1,
            "ambidextrous": 0.02,
        },
        "player_status_weights": {
            "active": 0.94,
            "injured": 0.02,
            "retired": 0.02,
            "inactive": 0.02,
        },
        "initial_skill_seed": {
            "mean": 1500,
            "std_dev": 275,
            "lower_bias": 100,
            "min": 500,
            "max": 3500,
        },
    },
    "name_assignment": {
        "name_region_fallback_order": ["state_province", "country"],
        "name_gender_mapping": {
            "male": "M",
            "female": "F",
        },
        "name_year_bucket_size": 1,
        "name_assignment_noise_rate": 0.03,
    },
    "regional": {
        "region_population_weight": 1.0,
        "regional_allocation_strategy": "selection_probability",
        "competitiveness_multiplier_default": 1.0,
        "competitiveness_noise_std_dev": 0.05,
        "min_players_per_region": 100,
        "regional_competitiveness_multipliers": {
            "Naples, FL": 1.25,
            "Phoenix, AZ": 1.15,
            "Austin, TX": 1.1,
            "Toronto, ON": 1.05,
            "rural_cold_climates": 0.85,
        },
    },
    "club_generation": {
        "clubs_per_75k_population": 1.0,
        "target_club_count": 10,
        "monthly_club_growth_rate": 0.003,
        "club_size_distribution": {
            "tiny": 0.35,
            "small": 0.4,
            "medium": 0.2,
            "large": 0.04,
            "mega": 0.01,
        },
        "capacity_ranges": {
            "tiny": [10, 30],
            "small": [31, 75],
            "medium": [76, 200],
            "large": [201, 500],
            "mega": [501, 1000],
        },
        "court_ranges": {
            "tiny": [1, 2],
            "small": [2, 4],
            "medium": [4, 8],
            "large": [8, 16],
            "mega": [16, 32],
        },
        "indoor_court_ratios": {
            "dedicated_facility": 0.75,
            "public_park": 0.0,
            "private_club": 0.45,
            "municipal_recreation": 0.35,
            "default": 0.3,
        },
        "unaffiliated_player_rate": 0.12,
        "multi_club_membership_rate": 0.06,
        "min_club_memberships_per_affiliated_player": 1,
        "max_club_memberships_per_player": 3,
        "secondary_membership_same_region_rate": 0.85,
        "club_assignment_noise_std_dev": 0.1,
        "club_size_power_law_alpha": 1.4,
        "max_club_fill_ratio": 1.0,
        "cross_region_assignment_enabled": False,
    },
    "club_assignment": {
        "weights": {
            "regional_proximity": 0.35,
            "club_type_compatibility": 0.2,
            "competitiveness_compatibility": 0.15,
            "capacity_factor": 0.1,
            "age_compatibility": 0.08,
            "socioeconomic_similarity": 0.05,
            "existing_social_relationships": 0.05,
            "random_noise": 0.02,
        },
        "stochastic_override_rate": 0.02,
    },
    "team_formation": {
        "target_team_count": None,
        "player_team_participation_rate": 0.90,
        "multi_team_player_rate": 0.08,
        "max_active_teams_per_player": 2,
        "same_club_team_rate": 0.78,
        "same_region_team_rate": 0.95,
        "rating_gap_mean": 175.0,
        "rating_gap_std_dev": 125.0,
        "rating_gap_max": 1500.0,
        "team_type_weights": {
            "mens_doubles": 0.30,
            "womens_doubles": 0.30,
            "mixed_doubles": 0.30,
            "open_doubles": 0.10,
        },
        "competitive_team_rate": 0.20,
        "team_persistence_probability_recreational": 0.25,
        "team_persistence_probability_competitive": 0.75,
        "dormant_team_reactivation_rate": 0.04,
        "retired_team_rate_on_dissolution": 0.10,
        "team_chemistry_weight": 0.35,
        "team_skill_balance_weight": 0.25,
        "team_club_proximity_weight": 0.25,
        "team_region_proximity_weight": 0.10,
        "team_prior_partnership_weight": 0.20,
        "team_noise_factor": 0.15,
        "allow_multiple_active_teams_per_scope": False,
    },
    "match_scheduling": {
        "monthly_matches_per_active_player_mean": 8.0,
        "monthly_matches_per_active_player_std_dev": 4.0,
        "match_volume_noise_factor": 0.15,
        "matches_per_team_per_month": 4.0,
        "weekend_concentration_bias": 1.75,
        "saturday_weight": 2.25,
        "sunday_weight": 1.85,
        "friday_weight": 1.2,
        "weekday_evening_weight": 1.0,
        "league_weekday_multiplier": 1.4,
        "tournament_weekend_multiplier": 2.5,
        "date_allocation_noise_level": "medium",
        "max_daily_match_share": 0.08,
        "holiday_modifier_enabled": True,
        "capacity_rebalance_enabled": True,
        "max_daily_matches_per_team": 2,
        "travel_radius_limit_miles": 50,
    },
    "match_types": {
        "weights": {
            "recreational": 0.55,
            "league": 0.2,
            "ladder": 0.1,
            "tournament": 0.1,
            "challenge": 0.04,
            "clinic": 0.01,
        },
        "class_by_type": {
            "recreational": "casual",
            "clinic": "casual",
            "challenge": "semi_competitive",
            "ladder": "semi_competitive",
            "league": "competitive",
            "tournament": "competitive",
        },
    },
    "matchmaking": {
        "rating_band_width": {
            "recreational": 400,
            "competitive": 150,
            "tournament": 100,
        },
        "skill_band_tolerances": {
            "under_3_0": 0.8,
            "3_0_to_4_0": 0.5,
            "4_0_to_5_0": 0.3,
            "5_0_plus": 0.15,
        },
        "matchmaking_noise_factor": 0.2,
        "rematch_penalty_window_days": 30,
        "locality_weight": 0.3,
        "quality_distribution": {
            "ideal": 0.65,
            "slight_mismatch": 0.25,
            "significant_mismatch": 0.08,
            "chaos": 0.02,
        },
        "pairing_source_weights_by_class": {
            "casual": {
                "competitive_team": 1.0,
                "ad_hoc": 0.0,
            },
            "semi_competitive": {
                "competitive_team": 1.0,
                "ad_hoc": 0.0,
            },
            "competitive": {
                "competitive_team": 1.0,
                "ad_hoc": 0.0,
            },
        },
        "pairing_source_overrides_by_type": {
            "clinic": {
                "competitive_team": 1.0,
                "ad_hoc": 0.0,
            },
            "tournament": {
                "competitive_team": 1.0,
                "ad_hoc": 0.0,
            },
        },
    },
    "games_and_scores": {
        "games_per_match": {
            "recreational": 1,
            "league": 2,
            "tournament": 3,
        },
        "game_target_score": 11,
        "win_by_two_rule_enabled": True,
        "win_by_two_extension_rate": 0.10,
        "score_noise_std_dev": 1.5,
        "upset_probability_boost": 0.15,
    },
    "hidden_performance_bias": {
        "enabled": False,
        "debug_enabled": False,
        "total_max_rating_points": 50,
        "age_advantage": {
            "enabled": True,
            "max_rating_points": 35,
            "points_per_year_gap": 1.25,
            "close_match_multiplier": 1.5,
            "close_match_competitiveness_threshold": 0.75,
        },
        "fatigue": {
            "enabled": True,
            "window_days": 14,
            "points_per_recent_game": 2,
            "max_rating_penalty": 25,
            "recovery_days_threshold": 3,
        },
        "regional_strength": {
            "enabled": True,
            "max_rating_points": 20,
            "map": {
                "Southern California": 18,
                "Florida": 15,
                "Texas": 10,
                "Arizona": 8,
                "Ontario": 4,
                "Developing Region": -8,
            },
        },
        "partnership_affinity": {
            "enabled": True,
            "same_club_bonus": 5,
            "matches_together_threshold_1": 10,
            "matches_together_bonus_1": 8,
            "matches_together_threshold_2": 25,
            "matches_together_bonus_2": 12,
            "recent_matches_bonus": 5,
            "new_team_penalty": -10,
            "max_rating_points": 25,
        },
        "experience": {
            "enabled": True,
            "max_rating_points": 15,
            "log_multiplier": 2,
            "close_match_multiplier": 1.25,
            "close_match_competitiveness_threshold": 0.75,
        },
    },
    "ratings": {
        "initial_rating_mean": 1500.0,
        "initial_rating_std_dev": 200.0,
        "rating_min": 0.0,
        "rating_max": 5000.0,
        "initial_rating_elite_tail_rate": 0.003,
        "initial_rating_elite_min": 4000.0,
        "initial_rating_elite_max": 4500.0,
        "k_factor_new_player": 48.0,
        "k_factor_established": 24.0,
        "k_factor_elite": 16.0,
        "k_factor_base": 24.0,
        "rating_noise_std_dev": 75.0,
        "rating_decay": 0.0,
        "rating_movement_warning_threshold": 300.0,
    },
    "confidence": {
        "initial_confidence_score": 0.1,
        "confidence_min": 0.0,
        "confidence_max": 1.0,
        "confidence_weight": 1.0,
        "confidence_recency_half_life_days": 90,
        "match_volume_weight": 0.4,
    },
    "availability_and_injury": {
        "availability_noise_level": "medium",
        "base_injury_rate": 0.005,
        "minor_injury_probability": 0.7,
        "moderate_injury_probability": 0.2,
        "acute_injury_probability": 0.08,
        "recurring_injury_probability": 0.02,
        "reinjury_probability": 0.03,
        "injury_performance_penalty_min": 0.02,
        "injury_performance_penalty_max": 0.15,
        "fatigue_accumulation_rate": 0.02,
        "fatigue_recovery_rate": 0.15,
    },
    "seasonality_weather_travel": {
        "seasonality_enabled": True,
        "seasonality_modifiers": {},
        "weather_impact_enabled": False,
        "court_surface_distribution": {},
        "travel_distance_penalty": 0.0,
    },
    "validation": {
        "validation_strictness": "standard",
        "validation_blocker_threshold": 0,
        "validation_error_threshold": 100,
        "allowed_warning_threshold": 1000,
        "validation_sample_size_distribution": 10000,
        "weekend_concentration_min": 0.4,
        "weekend_concentration_max": 0.6,
        "distribution_tolerance": 0.01,
    },
    "export": {
        "export_directory": "data/output",
        "export_format_primary": "parquet",
        "export_partition_strategy": "monthly",
        "export_compression_codec": "snappy",
        "export_included_table_groups": ["student_core", "reference"],
        "export_included_tables": [],
        "export_batch_on_completion": True,
    },
    "data_quality_injection": {
        "enabled": True,
        "level": "medium",
        "random_seed": 12345,
        "apply_to_release_types": [
            "initial_snapshot",
            "monthly_incremental",
        ],
        "write_instructor_manifest": True,
        "write_student_visible_quality_summary": False,
        "monthly_release_level_offset": -1,
        "global_limits": {
            "max_total_affected_rows_pct": 5.0,
            "max_affected_fields_per_row": 2,
            "prevent_primary_key_mutation": True,
            "prevent_foreign_key_mutation": True,
            "preserve_required_join_keys": True,
        },
        "table_rules": {
            "clubs": {
                "enabled": True,
                "issue_profile": "medium",
                "allowed_issue_types": [
                    "missing_optional_values",
                    "categorical_variants",
                    "soft_join_ambiguity",
                    "duplicate_like_rows",
                ],
            },
            "club_memberships": {
                "enabled": True,
                "issue_profile": "low",
                "allowed_issue_types": [
                    "missing_optional_values",
                    "categorical_variants",
                ],
            },
            "match_games": {
                "enabled": True,
                "issue_profile": "low",
                "allowed_issue_types": [
                    "numeric_outliers",
                ],
            },
            "match_team_players": {
                "enabled": True,
                "issue_profile": "low",
                "allowed_issue_types": [
                    "rounding_variants",
                ],
            },
            "match_teams": {
                "enabled": True,
                "issue_profile": "low",
                "allowed_issue_types": [
                    "rounding_variants",
                    "numeric_outliers",
                ],
            },
            "matches": {
                "enabled": True,
                "issue_profile": "medium",
                "allowed_issue_types": [
                    "missing_optional_values",
                    "categorical_variants",
                    "duplicate_like_rows",
                ],
            },
            "monthly_batches": {
                "enabled": True,
                "issue_profile": "low",
                "allowed_issue_types": [
                    "numeric_outliers",
                ],
            },
            "player_assessment_history": {
                "enabled": True,
                "issue_profile": "low",
                "allowed_issue_types": [
                    "missing_optional_values",
                    "numeric_outliers",
                    "rounding_variants",
                    "timestamp_jitter",
                ],
            },
            "players": {
                "enabled": True,
                "issue_profile": "medium",
                "allowed_issue_types": [
                    "name_case_variants",
                    "missing_optional_values",
                    "categorical_variants",
                    "rounding_variants",
                    "timestamp_jitter",
                ],
            },
            "player_registrations": {
                "enabled": True,
                "issue_profile": "low",
                "allowed_issue_types": [
                    "missing_optional_values",
                    "categorical_variants",
                    "rounding_variants",
                ],
            },
            "regions": {
                "enabled": True,
                "issue_profile": "low",
                "allowed_issue_types": [
                    "categorical_variants",
                    "soft_join_ambiguity",
                ],
            },
            "team_memberships": {
                "enabled": True,
                "issue_profile": "none",
                "allowed_issue_types": [],
            },
            "teams": {
                "enabled": True,
                "issue_profile": "low",
                "allowed_issue_types": [
                    "categorical_variants",
                    "soft_join_ambiguity",
                    "duplicate_like_rows",
                ],
            },
        },
    },
    "tournament_scoring": {
        "champion_points": 10,
        "runner_up_points": 6,
        "top_four_points": 3,
        "match_win_points": 1,
        "top_four_points_enabled": False,
    },
    "future_extensions": {
        "tournament_bracket_structures": {},
        "partnership_chemistry_evolution_rate": 0.05,
        "social_graph_decay_rate": 0.02,
        "community_hub_player_rate": 0.03,
        "data_quality_level": "standard",
        "missingness_rate": 0.0,
        "anomaly_rate": 0.0,
    },
}


def default_config_payload() -> dict[str, Any]:
    """Return a mutable copy of the default configuration payload."""
    return deepcopy(DEFAULT_CONFIG_PAYLOAD)
